### ISSUE TITLE
unable to inflate the view in fragment,kindly check

### ISSUE THREAD

**Issue by sharathyadhav1** [jszczygiel/AndroidYoutubeOverlay#2]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
import com.wroclawstudio.ytoverlay.YoutubeOverlayFragment;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ListView;

public class listfragment extends Fragment {
    View view;
    public String[] youtubeUrls = new String[]{
            "1KOaT1vdLmc",
            "PZbkF-15ObM",
            "tvY7Nw1i6Kw",
            "YwmbbcMHiQ0",
            "2b03hoW0TKc",
    };
     private YoutubeOverlayFragment ytPlayer;

```
@Override
@Nullable
public View onCreateView(LayoutInflater inflater,
        ViewGroup container, Bundle savedInstanceState) {
    // TODO Auto-generated method stub
    view = inflater.inflate(R.layout.activity_list_example, container,false);
      ListView list = (ListView)view.findViewById(R.id.listView1);
        list.setAdapter(new YoutubeListAdapter(getActivity(), youtubeUrls));
        ytPlayer = YoutubeOverlayFragment.newBuilder(Constants.YT_DEVELOPER_KEY, getActivity()).setScrollableViewId(R.id.listView1).buildAndAdd();
    return view;
}


class YoutubeListAdapter extends ArrayAdapter<String> {

    private final LayoutInflater inflater;

    public YoutubeListAdapter(Context context, String[] list) {
        super(context, 0, list);
        this.inflater = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
    }

    @Override
    public View getView(final int position, View convertView, ViewGroup parent) {
        final ViewHolder holder;
        if (convertView == null) {
            convertView = inflater.inflate(R.layout.row_main, parent, false);
            holder = new ViewHolder();
            holder.rowMainImage = convertView.findViewById(R.id.rowMainImage);
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }

        final String videoId = getItem(position);
        holder.rowMainImage.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                ytPlayer.onClick(holder.rowMainImage, videoId, position);
            }
        });

        return convertView;
    }

    class ViewHolder {
        View rowMainImage;
    }
}
```

**Comment by jszczygiel** [comment]
you should move this call:

```
ytPlayer = YoutubeOverlayFragment.newBuilder(Constants.YT_DEVELOPER_KEY, getActivity()).setScrollableViewId(R.id.listView1).buildAndAdd();
```

from onCreateView to onViewCreated as buildAndAdd() call is searching for listView1 in view hierarchy and 'view' has not been yet attached to its parent.

so it should like this:

```
@Override
@Nullable
public View onCreateView(LayoutInflater inflater,
        ViewGroup container, Bundle savedInstanceState) {
    // TODO Auto-generated method stub
    view = inflater.inflate(R.layout.activity_list_example, container,false);
      ListView list = (ListView)view.findViewById(R.id.listView1);
        list.setAdapter(new YoutubeListAdapter(getActivity(), youtubeUrls));

    return view;
}

@Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
ytPlayer = YoutubeOverlayFragment.newBuilder(Constants.YT_DEVELOPER_KEY, getActivity()).setScrollableViewId(R.id.listView1).buildAndAdd();
     }
```

**Comment by sharathyadhav1** [comment]
thanks a lot JAKUB YOU SAVED MY DAY !!!!!!!!!,if i need more help will get
back to you thanks in advance

LOVE YOU

thanks
sharath

**Comment by sharathyadhav1** [comment]
Dear jakub,
i really appreciate your prompt and precise response for the issues, it
would be really grateful if you could add touch intercept event to the
youtube fragment overlay , so it would be easy for scrolling the listview
with the video inside just like instagram does in iphone,it would be really
kind of you in solving this issue and helping me in completing my
project,eagerly awaiting for your reply

thanks and regards
sharath

**Comment by jszczygiel** [comment]
That is part of project roadmap. Unfortunately with no ETA. If you want you can fork project and make your own implementation and then create pull request.

**Comment by sharathyadhav1** [comment]
Sure jakib thanks for your support

**Comment by sharathyadhav1** [comment]
Dear jakub,
Now i am stuck with an issue video is not getting displayed in lollipop
version but displays in other versions

Issue:
White screen with audio working

Kindly help in solving this issue

**Comment by jszczygiel** [comment]
I think it requires to update yt lubt to higher version.
